//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace EmbodiedLab.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Robot action layout expected by the policy.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ActionSpace
    {

        [Newtonsoft.Json.JsonProperty("forward_step_meters", Required = Newtonsoft.Json.Required.Always)]
        public double ForwardStepMeters { get; set; }

        [Newtonsoft.Json.JsonProperty("layout", Required = Newtonsoft.Json.Required.Always, ItemConverterType = typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public System.Collections.Generic.ICollection<Layout> Layout { get; set; } = new System.Collections.ObjectModel.Collection<Layout>();

        [Newtonsoft.Json.JsonProperty("step_duration_seconds", Required = Newtonsoft.Json.Required.Always)]
        public double StepDurationSeconds { get; set; }

        [Newtonsoft.Json.JsonProperty("turn_degrees_per_step", Required = Newtonsoft.Json.Required.Always)]
        public double TurnDegreesPerStep { get; set; }

        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ActionSpaceType Type { get; set; }

    }

    /// <summary>
    /// Supported robot action space families.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ActionSpaceType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"continuous")]
        Continuous = 0,


    }

    /// <summary>
    /// Location and format of a result artifact.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ArtifactLocation
    {

        [Newtonsoft.Json.JsonProperty("bucket", Required = Newtonsoft.Json.Required.Always)]
        public string Bucket { get; set; }

        [Newtonsoft.Json.JsonProperty("format", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ArtifactLocationFormat Format { get; set; }

        [Newtonsoft.Json.JsonProperty("path", Required = Newtonsoft.Json.Required.Always)]
        public string Path { get; set; }

        [Newtonsoft.Json.JsonProperty("sha256", Required = Newtonsoft.Json.Required.Always)]
        public string Sha256 { get; set; }

        [Newtonsoft.Json.JsonProperty("size_bytes", Required = Newtonsoft.Json.Required.Always)]
        public int SizeBytes { get; set; }

        [Newtonsoft.Json.JsonProperty("storage", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ArtifactStorage Storage { get; set; }

    }

    /// <summary>
    /// Supported artifact storage backends.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ArtifactStorage
    {

        [System.Runtime.Serialization.EnumMember(Value = @"gcs")]
        Gcs = 0,


    }

    /// <summary>
    /// Axis-aligned world bounds on the x/z plane.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Bounds2D
    {

        [Newtonsoft.Json.JsonProperty("max", Required = Newtonsoft.Json.Required.Always)]
        public Position2D Max { get; set; } = new Position2D();

        [Newtonsoft.Json.JsonProperty("min", Required = Newtonsoft.Json.Required.Always)]
        public Position2D Min { get; set; } = new Position2D();

    }

    /// <summary>
    /// Reward component emitted on collisions.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class CollisionRewardComponent : RewardComponent
    {

    }

    /// <summary>
    /// Compatibility metadata required by EmbodiedLab clients.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Compatibility
    {

        [Newtonsoft.Json.JsonProperty("robot_version", Required = Newtonsoft.Json.Required.Always)]
        public string RobotVersion { get; set; }

        [Newtonsoft.Json.JsonProperty("sensor_version", Required = Newtonsoft.Json.Required.Always)]
        public string SensorVersion { get; set; }

    }

    /// <summary>
    /// Supported world coordinate systems for scenario bundles.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum CoordinateSystem
    {

        [System.Runtime.Serialization.EnumMember(Value = @"left_handed_y_up_meters")]
        LeftHandedYUpMeters = 0,


    }

    /// <summary>
    /// Metadata about the tool that created a scenario bundle.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class CreatedBy
    {

        [Newtonsoft.Json.JsonProperty("tool", Required = Newtonsoft.Json.Required.Always)]
        public string Tool { get; set; }

        [Newtonsoft.Json.JsonProperty("version", Required = Newtonsoft.Json.Required.Always)]
        public string Version { get; set; }

    }

    /// <summary>
    /// Reward based on distance progress toward a target object.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class DistanceDeltaRewardComponent : RewardComponent
    {

        [Newtonsoft.Json.JsonProperty("minimum_delta_meters", Required = Newtonsoft.Json.Required.Always)]
        public double MinimumDeltaMeters { get; set; }

        [Newtonsoft.Json.JsonProperty("target", Required = Newtonsoft.Json.Required.Always)]
        public string Target { get; set; }

    }

    /// <summary>
    /// Forward distance sensor configuration.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class DistanceSensor : SensorSpec
    {

        [Newtonsoft.Json.JsonProperty("direction", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public SensorDirection Direction { get; set; }

        [Newtonsoft.Json.JsonProperty("range_meters", Required = Newtonsoft.Json.Required.Always)]
        public double RangeMeters { get; set; }

    }

    /// <summary>
    /// Structured failure details for failed result bundles.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ErrorReport
    {

        [Newtonsoft.Json.JsonProperty("details", Required = Newtonsoft.Json.Required.AllowNull)]
        public string Details { get; set; }

        [Newtonsoft.Json.JsonProperty("message", Required = Newtonsoft.Json.Required.Always)]
        public string Message { get; set; }

    }

    /// <summary>
    /// One deterministic evaluation Replay chunk.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class EvalReplayBundleChunk : ReplayBundleChunk
    {

        [Newtonsoft.Json.JsonProperty("avg_reward", Required = Newtonsoft.Json.Required.Always)]
        public double AvgReward { get; set; }

        [Newtonsoft.Json.JsonProperty("avg_steps", Required = Newtonsoft.Json.Required.Always)]
        public double AvgSteps { get; set; }

        [Newtonsoft.Json.JsonProperty("end_step", Required = Newtonsoft.Json.Required.AllowNull)]
        public object EndStep { get; set; }

        [Newtonsoft.Json.JsonProperty("episode_count", Required = Newtonsoft.Json.Required.Always)]
        public int EpisodeCount { get; set; }

        [Newtonsoft.Json.JsonProperty("format", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public EvalReplayBundleChunkFormat Format { get; set; }

        [Newtonsoft.Json.JsonProperty("path", Required = Newtonsoft.Json.Required.Always)]
        public string Path { get; set; }

        [Newtonsoft.Json.JsonProperty("policy_mode", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public EvalReplayBundleChunkPolicyMode PolicyMode { get; set; }

        [Newtonsoft.Json.JsonProperty("start_step", Required = Newtonsoft.Json.Required.AllowNull)]
        public object StartStep { get; set; }

        [Newtonsoft.Json.JsonProperty("step_count", Required = Newtonsoft.Json.Required.Always)]
        public int StepCount { get; set; }

        [Newtonsoft.Json.JsonProperty("success_rate", Required = Newtonsoft.Json.Required.Always)]
        public double SuccessRate { get; set; }

    }

    /// <summary>
    /// Forward semantic camera sensor configuration.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ForwardCameraSensor : SensorSpec
    {

        [Newtonsoft.Json.JsonProperty("far_clip_meters", Required = Newtonsoft.Json.Required.Always)]
        public double FarClipMeters { get; set; }

        [Newtonsoft.Json.JsonProperty("height", Required = Newtonsoft.Json.Required.Always)]
        public int Height { get; set; }

        [Newtonsoft.Json.JsonProperty("mount_height_max_meters", Required = Newtonsoft.Json.Required.AllowNull)]
        public double? MountHeightMaxMeters { get; set; }

        [Newtonsoft.Json.JsonProperty("mount_height_meters", Required = Newtonsoft.Json.Required.Always)]
        public double MountHeightMeters { get; set; }

        [Newtonsoft.Json.JsonProperty("mount_height_min_meters", Required = Newtonsoft.Json.Required.AllowNull)]
        public double? MountHeightMinMeters { get; set; }

        [Newtonsoft.Json.JsonProperty("near_clip_meters", Required = Newtonsoft.Json.Required.Always)]
        public double NearClipMeters { get; set; }

        [Newtonsoft.Json.JsonProperty("observation_name", Required = Newtonsoft.Json.Required.Always)]
        public string ObservationName { get; set; }

        [Newtonsoft.Json.JsonProperty("pitch_degrees", Required = Newtonsoft.Json.Required.Always)]
        public double PitchDegrees { get; set; }

        [Newtonsoft.Json.JsonProperty("semantic_mode", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public SemanticMode SemanticMode { get; set; }

        [Newtonsoft.Json.JsonProperty("vertical_fov_degrees", Required = Newtonsoft.Json.Required.Always)]
        public double VerticalFovDegrees { get; set; }

        [Newtonsoft.Json.JsonProperty("width", Required = Newtonsoft.Json.Required.Always)]
        public int Width { get; set; }

    }

    /// <summary>
    /// Goal region used for navigation training.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GoalSpec
    {

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; }

        [Newtonsoft.Json.JsonProperty("position", Required = Newtonsoft.Json.Required.Always)]
        public Position2D Position { get; set; } = new Position2D();

        [Newtonsoft.Json.JsonProperty("radius", Required = Newtonsoft.Json.Required.Always)]
        public double Radius { get; set; }

    }

    /// <summary>
    /// Goal-relative numeric observation consumed by the policy.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GoalVectorSensor : SensorSpec
    {

        [Newtonsoft.Json.JsonProperty("observation_name", Required = Newtonsoft.Json.Required.Always)]
        public string ObservationName { get; set; }

        [Newtonsoft.Json.JsonProperty("target", Required = Newtonsoft.Json.Required.Always)]
        public string Target { get; set; }

        [Newtonsoft.Json.JsonProperty("values", Required = Newtonsoft.Json.Required.Always, ItemConverterType = typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public System.Collections.Generic.ICollection<Values> Values { get; set; } = new System.Collections.ObjectModel.Collection<Values>();

    }

    /// <summary>
    /// Penalty enabled when forward action stays below a threshold.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class MaximumAbsoluteForwardRewardComponent : RewardComponent
    {

        [Newtonsoft.Json.JsonProperty("maximum_absolute_forward", Required = Newtonsoft.Json.Required.Always)]
        public double MaximumAbsoluteForward { get; set; }

    }

    /// <summary>
    /// Penalty enabled above an absolute goal-angle threshold.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class MinimumAbsoluteAngleRewardComponent : RewardComponent
    {

        [Newtonsoft.Json.JsonProperty("minimum_absolute_angle_degrees", Required = Newtonsoft.Json.Required.Always)]
        public double MinimumAbsoluteAngleDegrees { get; set; }

    }

    /// <summary>
    /// Input metadata for a client-loadable model artifact.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ModelInput
    {

        [Newtonsoft.Json.JsonProperty("dtype", Required = Newtonsoft.Json.Required.Always)]
        public string Dtype { get; set; }

        [Newtonsoft.Json.JsonProperty("layout", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<string> Layout { get; set; } = new System.Collections.ObjectModel.Collection<string>();

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; }

        [Newtonsoft.Json.JsonProperty("shape", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<int> Shape { get; set; } = new System.Collections.ObjectModel.Collection<int>();

    }

    /// <summary>
    /// Output metadata for a client-loadable model artifact.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ModelOutput
    {

        [Newtonsoft.Json.JsonProperty("action_mapping", Required = Newtonsoft.Json.Required.AllowNull)]
        public System.Collections.Generic.IDictionary<string, string> ActionMapping { get; set; }

        [Newtonsoft.Json.JsonProperty("layout", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<string> Layout { get; set; } = new System.Collections.ObjectModel.Collection<string>();

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; }

    }

    /// <summary>
    /// Canonical ONNX Runtime artifact metadata.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class OnnxModelArtifactLocation
    {

        [Newtonsoft.Json.JsonProperty("bucket", Required = Newtonsoft.Json.Required.Always)]
        public string Bucket { get; set; }

        [Newtonsoft.Json.JsonProperty("format", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public OnnxModelArtifactLocationFormat Format { get; set; }

        [Newtonsoft.Json.JsonProperty("inputs", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<ModelInput> Inputs { get; set; } = new System.Collections.ObjectModel.Collection<ModelInput>();

        [Newtonsoft.Json.JsonProperty("opset_version", Required = Newtonsoft.Json.Required.Always)]
        public OnnxModelArtifactLocationOpsetVersion OpsetVersion { get; set; }

        [Newtonsoft.Json.JsonProperty("output", Required = Newtonsoft.Json.Required.Always)]
        public ModelOutput Output { get; set; } = new ModelOutput();

        [Newtonsoft.Json.JsonProperty("path", Required = Newtonsoft.Json.Required.Always)]
        public string Path { get; set; }

        [Newtonsoft.Json.JsonProperty("sha256", Required = Newtonsoft.Json.Required.Always)]
        public string Sha256 { get; set; }

        [Newtonsoft.Json.JsonProperty("size_bytes", Required = Newtonsoft.Json.Required.Always)]
        public int SizeBytes { get; set; }

        [Newtonsoft.Json.JsonProperty("storage", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ArtifactStorage Storage { get; set; }

        [Newtonsoft.Json.JsonProperty("target", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public OnnxModelArtifactLocationTarget Target { get; set; }

    }

    /// <summary>
    /// Reward component emitted at each simulation step.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class PerStepRewardComponent : RewardComponent
    {

    }

    /// <summary>
    /// Robot pose on the x/z plane.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Pose2D
    {

        [Newtonsoft.Json.JsonProperty("position", Required = Newtonsoft.Json.Required.Always)]
        public Position2D Position { get; set; } = new Position2D();

        [Newtonsoft.Json.JsonProperty("rotation_y_degrees", Required = Newtonsoft.Json.Required.Always)]
        public double RotationYDegrees { get; set; }

    }

    /// <summary>
    /// A point on the horizontal x/z plane.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Position2D
    {

        [Newtonsoft.Json.JsonProperty("x", Required = Newtonsoft.Json.Required.Always)]
        public double X { get; set; }

        [Newtonsoft.Json.JsonProperty("z", Required = Newtonsoft.Json.Required.Always)]
        public double Z { get; set; }

    }

    /// <summary>
    /// Training progress snapshot stored in each result document.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Progress
    {

        [Newtonsoft.Json.JsonProperty("current_step", Required = Newtonsoft.Json.Required.Always)]
        public int CurrentStep { get; set; }

        [Newtonsoft.Json.JsonProperty("message", Required = Newtonsoft.Json.Required.Always)]
        public string Message { get; set; }

        [Newtonsoft.Json.JsonProperty("phase", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ResultStatus Phase { get; set; }

        [Newtonsoft.Json.JsonProperty("total_steps", Required = Newtonsoft.Json.Required.Always)]
        public int TotalSteps { get; set; }

    }

    /// <summary>
    /// Action values emitted for a replay step.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayAction
    {

        [Newtonsoft.Json.JsonProperty("values", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<ReplayActionValue> Values { get; set; } = new System.Collections.ObjectModel.Collection<ReplayActionValue>();

    }

    [Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "name")]
    [JsonInheritanceAttribute("forward", typeof(ReplayForwardActionValue))]
    [JsonInheritanceAttribute("turn", typeof(ReplayTurnActionValue))]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public abstract partial class ReplayActionValue
    {

        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.Always)]
        public double Value { get; set; }

    }

    [Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "phase")]
    [JsonInheritanceAttribute("eval", typeof(EvalReplayBundleChunk))]
    [JsonInheritanceAttribute("train", typeof(TrainReplayBundleChunk))]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public abstract partial class ReplayBundleChunk
    {

        [Newtonsoft.Json.JsonProperty("checkpoint_step", Required = Newtonsoft.Json.Required.Always)]
        public int CheckpointStep { get; set; }

        [Newtonsoft.Json.JsonProperty("sha256", Required = Newtonsoft.Json.Required.Always)]
        public string Sha256 { get; set; }

        [Newtonsoft.Json.JsonProperty("size_bytes", Required = Newtonsoft.Json.Required.Always)]
        public int SizeBytes { get; set; }

    }

    /// <summary>
    /// Manifest describing the chunks in one Replay Bundle.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayBundleManifest
    {

        [Newtonsoft.Json.JsonProperty("chunks", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<ReplayBundleChunk> Chunks { get; set; } = new System.Collections.ObjectModel.Collection<ReplayBundleChunk>();

        [Newtonsoft.Json.JsonProperty("job_id", Required = Newtonsoft.Json.Required.Always)]
        public string JobId { get; set; }

        [Newtonsoft.Json.JsonProperty("scenario_id", Required = Newtonsoft.Json.Required.Always)]
        public string ScenarioId { get; set; }

        [Newtonsoft.Json.JsonProperty("schema_version", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ReplayBundleManifestSchemaVersion SchemaVersion { get; set; }

        [Newtonsoft.Json.JsonProperty("total_timesteps", Required = Newtonsoft.Json.Required.Always)]
        public int TotalTimesteps { get; set; }

    }

    /// <summary>
    /// A compact event emitted during replay.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayEvent
    {

        [Newtonsoft.Json.JsonProperty("message", Required = Newtonsoft.Json.Required.AllowNull)]
        public string Message { get; set; }

        [Newtonsoft.Json.JsonProperty("object_id", Required = Newtonsoft.Json.Required.AllowNull)]
        public string ObjectId { get; set; }

        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; set; }

    }

    /// <summary>
    /// The forward component of the continuous action.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayForwardActionValue : ReplayActionValue
    {

    }

    /// <summary>
    /// One JSON Lines row in a Replay Log.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayLogStep
    {

        [Newtonsoft.Json.JsonProperty("action", Required = Newtonsoft.Json.Required.Always)]
        public ReplayAction Action { get; set; } = new ReplayAction();

        [Newtonsoft.Json.JsonProperty("checkpoint_step", Required = Newtonsoft.Json.Required.Always)]
        public int CheckpointStep { get; set; }

        [Newtonsoft.Json.JsonProperty("env_index", Required = Newtonsoft.Json.Required.Always)]
        public int EnvIndex { get; set; }

        [Newtonsoft.Json.JsonProperty("episode_id", Required = Newtonsoft.Json.Required.Always)]
        public string EpisodeId { get; set; }

        [Newtonsoft.Json.JsonProperty("events", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<ReplayEvent> Events { get; set; } = new System.Collections.ObjectModel.Collection<ReplayEvent>();

        [Newtonsoft.Json.JsonProperty("job_id", Required = Newtonsoft.Json.Required.Always)]
        public string JobId { get; set; }

        [Newtonsoft.Json.JsonProperty("phase", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ReplayLogStepPhase Phase { get; set; }

        [Newtonsoft.Json.JsonProperty("policy_mode", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ReplayLogStepPolicyMode PolicyMode { get; set; }

        [Newtonsoft.Json.JsonProperty("reward", Required = Newtonsoft.Json.Required.Always)]
        public ReplayReward Reward { get; set; } = new ReplayReward();

        [Newtonsoft.Json.JsonProperty("robot", Required = Newtonsoft.Json.Required.Always)]
        public ReplayRobotState Robot { get; set; } = new ReplayRobotState();

        [Newtonsoft.Json.JsonProperty("scenario_id", Required = Newtonsoft.Json.Required.Always)]
        public string ScenarioId { get; set; }

        [Newtonsoft.Json.JsonProperty("schema_version", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ReplayLogStepSchemaVersion SchemaVersion { get; set; }

        [Newtonsoft.Json.JsonProperty("sensors", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<ReplaySensorSummary> Sensors { get; set; } = new System.Collections.ObjectModel.Collection<ReplaySensorSummary>();

        [Newtonsoft.Json.JsonProperty("step_index", Required = Newtonsoft.Json.Required.Always)]
        public int StepIndex { get; set; }

        [Newtonsoft.Json.JsonProperty("terminated", Required = Newtonsoft.Json.Required.Always)]
        public bool Terminated { get; set; }

        [Newtonsoft.Json.JsonProperty("termination_reason", Required = Newtonsoft.Json.Required.AllowNull)]
        public string TerminationReason { get; set; }

        [Newtonsoft.Json.JsonProperty("time_seconds", Required = Newtonsoft.Json.Required.Always)]
        public double TimeSeconds { get; set; }

    }

    /// <summary>
    /// A named scalar value in a JsonUtility-friendly replay payload.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayNamedValue
    {

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; }

        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.Always)]
        public double Value { get; set; }

    }

    /// <summary>
    /// A continuous replay position on the x/z plane.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayPosition
    {

        [Newtonsoft.Json.JsonProperty("x", Required = Newtonsoft.Json.Required.Always)]
        public double X { get; set; }

        [Newtonsoft.Json.JsonProperty("z", Required = Newtonsoft.Json.Required.Always)]
        public double Z { get; set; }

    }

    /// <summary>
    /// Reward values emitted for a replay step.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayReward
    {

        [Newtonsoft.Json.JsonProperty("components", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<ReplayNamedValue> Components { get; set; } = new System.Collections.ObjectModel.Collection<ReplayNamedValue>();

        [Newtonsoft.Json.JsonProperty("total", Required = Newtonsoft.Json.Required.Always)]
        public double Total { get; set; }

    }

    /// <summary>
    /// Robot state emitted in a replay step.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayRobotState
    {

        [Newtonsoft.Json.JsonProperty("position", Required = Newtonsoft.Json.Required.Always)]
        public ReplayPosition Position { get; set; } = new ReplayPosition();

        [Newtonsoft.Json.JsonProperty("rotation_y_degrees", Required = Newtonsoft.Json.Required.Always)]
        public double RotationYDegrees { get; set; }

    }

    /// <summary>
    /// A compact sensor summary emitted during replay.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplaySensorSummary
    {

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; }

        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; set; }

        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.Always)]
        public double Value { get; set; }

    }

    /// <summary>
    /// The turn component of the continuous action.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayTurnActionValue : ReplayActionValue
    {

    }

    /// <summary>
    /// Exact library, hyperparameters, and resources used by a training run.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ResolvedTrainingConfig
    {

        [Newtonsoft.Json.JsonProperty("algorithm", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ResolvedTrainingConfigAlgorithm Algorithm { get; set; }

        [Newtonsoft.Json.JsonProperty("batch_size", Required = Newtonsoft.Json.Required.Always)]
        public int BatchSize { get; set; }

        [Newtonsoft.Json.JsonProperty("clip_range", Required = Newtonsoft.Json.Required.Always)]
        public double ClipRange { get; set; }

        [Newtonsoft.Json.JsonProperty("clip_range_vf", Required = Newtonsoft.Json.Required.AllowNull)]
        public double? ClipRangeVf { get; set; }

        [Newtonsoft.Json.JsonProperty("cpu_count", Required = Newtonsoft.Json.Required.Always)]
        public int CpuCount { get; set; }

        [Newtonsoft.Json.JsonProperty("device", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ResolvedTrainingConfigDevice Device { get; set; }

        [Newtonsoft.Json.JsonProperty("ent_coef", Required = Newtonsoft.Json.Required.Always)]
        public double EntCoef { get; set; }

        [Newtonsoft.Json.JsonProperty("eval_episodes", Required = Newtonsoft.Json.Required.Always)]
        public int EvalEpisodes { get; set; }

        [Newtonsoft.Json.JsonProperty("gae_lambda", Required = Newtonsoft.Json.Required.Always)]
        public double GaeLambda { get; set; }

        [Newtonsoft.Json.JsonProperty("gamma", Required = Newtonsoft.Json.Required.Always)]
        public double Gamma { get; set; }

        [Newtonsoft.Json.JsonProperty("learning_rate", Required = Newtonsoft.Json.Required.Always)]
        public double LearningRate { get; set; }

        [Newtonsoft.Json.JsonProperty("library", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ResolvedTrainingConfigLibrary Library { get; set; }

        [Newtonsoft.Json.JsonProperty("library_version", Required = Newtonsoft.Json.Required.Always)]
        public string LibraryVersion { get; set; }

        [Newtonsoft.Json.JsonProperty("max_episode_steps", Required = Newtonsoft.Json.Required.Always)]
        public int MaxEpisodeSteps { get; set; }

        [Newtonsoft.Json.JsonProperty("max_grad_norm", Required = Newtonsoft.Json.Required.Always)]
        public double MaxGradNorm { get; set; }

        [Newtonsoft.Json.JsonProperty("n_envs", Required = Newtonsoft.Json.Required.Always)]
        public int NEnvs { get; set; }

        [Newtonsoft.Json.JsonProperty("n_epochs", Required = Newtonsoft.Json.Required.Always)]
        public int NEpochs { get; set; }

        [Newtonsoft.Json.JsonProperty("n_steps", Required = Newtonsoft.Json.Required.Always)]
        public int NSteps { get; set; }

        [Newtonsoft.Json.JsonProperty("normalize_advantage", Required = Newtonsoft.Json.Required.Always)]
        public bool NormalizeAdvantage { get; set; }

        [Newtonsoft.Json.JsonProperty("randomize_start", Required = Newtonsoft.Json.Required.Always)]
        public bool RandomizeStart { get; set; }

        [Newtonsoft.Json.JsonProperty("replay_eval_interval_steps", Required = Newtonsoft.Json.Required.Always)]
        public int ReplayEvalIntervalSteps { get; set; }

        [Newtonsoft.Json.JsonProperty("replay_train_chunk_steps", Required = Newtonsoft.Json.Required.Always)]
        public int ReplayTrainChunkSteps { get; set; }

        [Newtonsoft.Json.JsonProperty("requested_cpu_count", Required = Newtonsoft.Json.Required.AllowNull)]
        public int? RequestedCpuCount { get; set; }

        [Newtonsoft.Json.JsonProperty("requested_torch_num_threads", Required = Newtonsoft.Json.Required.AllowNull)]
        public int? RequestedTorchNumThreads { get; set; }

        [Newtonsoft.Json.JsonProperty("sde_sample_freq", Required = Newtonsoft.Json.Required.Always)]
        public int SdeSampleFreq { get; set; }

        [Newtonsoft.Json.JsonProperty("seed", Required = Newtonsoft.Json.Required.Always)]
        public long Seed { get; set; }

        [Newtonsoft.Json.JsonProperty("stats_window_size", Required = Newtonsoft.Json.Required.Always)]
        public int StatsWindowSize { get; set; }

        [Newtonsoft.Json.JsonProperty("target_kl", Required = Newtonsoft.Json.Required.AllowNull)]
        public double? TargetKl { get; set; }

        [Newtonsoft.Json.JsonProperty("timesteps", Required = Newtonsoft.Json.Required.Always)]
        public int Timesteps { get; set; }

        [Newtonsoft.Json.JsonProperty("torch_num_threads", Required = Newtonsoft.Json.Required.Always)]
        public int TorchNumThreads { get; set; }

        [Newtonsoft.Json.JsonProperty("use_sde", Required = Newtonsoft.Json.Required.Always)]
        public bool UseSde { get; set; }

        [Newtonsoft.Json.JsonProperty("vf_coef", Required = Newtonsoft.Json.Required.Always)]
        public double VfCoef { get; set; }

    }

    /// <summary>
    /// Artifacts produced by a training run.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ResultArtifacts
    {

        [Newtonsoft.Json.JsonProperty("onnx_model", Required = Newtonsoft.Json.Required.AllowNull)]
        public OnnxModelArtifactLocation OnnxModel { get; set; }

        [Newtonsoft.Json.JsonProperty("replay_bundle", Required = Newtonsoft.Json.Required.AllowNull)]
        public ArtifactLocation ReplayBundle { get; set; }

        [Newtonsoft.Json.JsonProperty("sentis_model", Required = Newtonsoft.Json.Required.AllowNull)]
        public SentisModelArtifactLocation SentisModel { get; set; }

    }

    /// <summary>
    /// Client-facing training result bundle.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ResultBundle
    {

        [Newtonsoft.Json.JsonProperty("artifacts", Required = Newtonsoft.Json.Required.Always)]
        public ResultArtifacts Artifacts { get; set; } = new ResultArtifacts();

        [Newtonsoft.Json.JsonProperty("compatibility", Required = Newtonsoft.Json.Required.Always)]
        public ResultCompatibility Compatibility { get; set; } = new ResultCompatibility();

        [Newtonsoft.Json.JsonProperty("error", Required = Newtonsoft.Json.Required.AllowNull)]
        public ErrorReport Error { get; set; }

        [Newtonsoft.Json.JsonProperty("job_id", Required = Newtonsoft.Json.Required.Always)]
        public string JobId { get; set; }

        [Newtonsoft.Json.JsonProperty("scenario_id", Required = Newtonsoft.Json.Required.Always)]
        public string ScenarioId { get; set; }

        [Newtonsoft.Json.JsonProperty("schema_version", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ResultBundleSchemaVersion SchemaVersion { get; set; }

        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ResultBundleStatus Status { get; set; }

        [Newtonsoft.Json.JsonProperty("summary", Required = Newtonsoft.Json.Required.AllowNull)]
        public TrainingSummary Summary { get; set; }

    }

    /// <summary>
    /// Compatibility metadata needed by clients when loading a result.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ResultCompatibility
    {

        [Newtonsoft.Json.JsonProperty("action_layout", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<string> ActionLayout { get; set; } = new System.Collections.ObjectModel.Collection<string>();

        [Newtonsoft.Json.JsonProperty("observation_layout", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<string> ObservationLayout { get; set; } = new System.Collections.ObjectModel.Collection<string>();

        [Newtonsoft.Json.JsonProperty("robot_version", Required = Newtonsoft.Json.Required.Always)]
        public string RobotVersion { get; set; }

        [Newtonsoft.Json.JsonProperty("scenario_schema_version", Required = Newtonsoft.Json.Required.Always)]
        public string ScenarioSchemaVersion { get; set; }

        [Newtonsoft.Json.JsonProperty("sensor_version", Required = Newtonsoft.Json.Required.Always)]
        public string SensorVersion { get; set; }

    }

    /// <summary>
    /// Full result document written to Firestore.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ResultDocument
    {

        [Newtonsoft.Json.JsonProperty("error", Required = Newtonsoft.Json.Required.AllowNull)]
        public string Error { get; set; }

        [Newtonsoft.Json.JsonProperty("progress", Required = Newtonsoft.Json.Required.Always)]
        public Progress Progress { get; set; } = new Progress();

        [Newtonsoft.Json.JsonProperty("result_bundle", Required = Newtonsoft.Json.Required.AllowNull)]
        public ResultBundle ResultBundle { get; set; }

        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ResultStatus Status { get; set; }

        [Newtonsoft.Json.JsonProperty("submission_id", Required = Newtonsoft.Json.Required.Always)]
        public string SubmissionId { get; set; }

        [Newtonsoft.Json.JsonProperty("updated_at", Required = Newtonsoft.Json.Required.Always)]
        public string UpdatedAt { get; set; }

    }

    /// <summary>
    /// Lifecycle states of a training result.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ResultStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"queued")]
        Queued = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"starting")]
        Starting = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"running")]
        Running = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"cancelling")]
        Cancelling = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"cancelled")]
        Cancelled = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"completed")]
        Completed = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"failed")]
        Failed = 6,


    }

    [Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "type")]
    [JsonInheritanceAttribute("collision", typeof(CollisionRewardComponent))]
    [JsonInheritanceAttribute("distance_delta", typeof(DistanceDeltaRewardComponent))]
    [JsonInheritanceAttribute("maximum_absolute_forward", typeof(MaximumAbsoluteForwardRewardComponent))]
    [JsonInheritanceAttribute("minimum_absolute_angle", typeof(MinimumAbsoluteAngleRewardComponent))]
    [JsonInheritanceAttribute("per_step", typeof(PerStepRewardComponent))]
    [JsonInheritanceAttribute("terminal_reward", typeof(TerminalRewardComponent))]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public abstract partial class RewardComponent
    {

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; }

        [Newtonsoft.Json.JsonProperty("weight", Required = Newtonsoft.Json.Required.Always)]
        public double Weight { get; set; }

    }

    /// <summary>
    /// Declarative reward configuration for training.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class RewardSpec
    {

        [Newtonsoft.Json.JsonProperty("components", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<RewardComponent> Components { get; set; } = new System.Collections.ObjectModel.Collection<RewardComponent>();

    }

    /// <summary>
    /// Robot descriptor for a scenario bundle.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class RobotSpec
    {

        [Newtonsoft.Json.JsonProperty("action_space", Required = Newtonsoft.Json.Required.Always)]
        public ActionSpace ActionSpace { get; set; } = new ActionSpace();

        [Newtonsoft.Json.JsonProperty("radius", Required = Newtonsoft.Json.Required.Always)]
        public double Radius { get; set; }

        [Newtonsoft.Json.JsonProperty("start_pose", Required = Newtonsoft.Json.Required.Always)]
        public Pose2D StartPose { get; set; } = new Pose2D();

        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public RobotType Type { get; set; }

    }

    /// <summary>
    /// Robot archetypes supported by the current scenario contract.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum RobotType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"simple_robot")]
        SimpleRobot = 0,


    }

    /// <summary>
    /// Top-level request body for POST /submissions.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ScenarioBundle
    {

        [Newtonsoft.Json.JsonProperty("compatibility", Required = Newtonsoft.Json.Required.Always)]
        public Compatibility Compatibility { get; set; } = new Compatibility();

        [Newtonsoft.Json.JsonProperty("created_by", Required = Newtonsoft.Json.Required.Always)]
        public CreatedBy CreatedBy { get; set; } = new CreatedBy();

        [Newtonsoft.Json.JsonProperty("reward", Required = Newtonsoft.Json.Required.Always)]
        public RewardSpec Reward { get; set; } = new RewardSpec();

        [Newtonsoft.Json.JsonProperty("robot", Required = Newtonsoft.Json.Required.Always)]
        public RobotSpec Robot { get; set; } = new RobotSpec();

        [Newtonsoft.Json.JsonProperty("scenario_id", Required = Newtonsoft.Json.Required.Always)]
        public string ScenarioId { get; set; }

        [Newtonsoft.Json.JsonProperty("schema_version", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ScenarioBundleSchemaVersion SchemaVersion { get; set; }

        [Newtonsoft.Json.JsonProperty("sensors", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<SensorSpec> Sensors { get; set; } = new System.Collections.ObjectModel.Collection<SensorSpec>();

        [Newtonsoft.Json.JsonProperty("training", Required = Newtonsoft.Json.Required.Always)]
        public TrainingSpec Training { get; set; } = new TrainingSpec();

        [Newtonsoft.Json.JsonProperty("world", Required = Newtonsoft.Json.Required.Always)]
        public WorldSpec World { get; set; } = new WorldSpec();

    }

    /// <summary>
    /// Supported semantic camera encodings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SemanticMode
    {

        [System.Runtime.Serialization.EnumMember(Value = @"traversable_vs_blocked")]
        TraversableVsBlocked = 0,


    }

    /// <summary>
    /// Supported distance sensor directions.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SensorDirection
    {

        [System.Runtime.Serialization.EnumMember(Value = @"forward")]
        Forward = 0,


    }

    [Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "type")]
    [JsonInheritanceAttribute("distance_sensor", typeof(DistanceSensor))]
    [JsonInheritanceAttribute("forward_camera", typeof(ForwardCameraSensor))]
    [JsonInheritanceAttribute("goal_vector", typeof(GoalVectorSensor))]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public abstract partial class SensorSpec
    {

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; }

    }

    /// <summary>
    /// Canonical Unity Sentis artifact metadata.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class SentisModelArtifactLocation
    {

        [Newtonsoft.Json.JsonProperty("bucket", Required = Newtonsoft.Json.Required.Always)]
        public string Bucket { get; set; }

        [Newtonsoft.Json.JsonProperty("format", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public SentisModelArtifactLocationFormat Format { get; set; }

        [Newtonsoft.Json.JsonProperty("inputs", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<ModelInput> Inputs { get; set; } = new System.Collections.ObjectModel.Collection<ModelInput>();

        [Newtonsoft.Json.JsonProperty("opset_version", Required = Newtonsoft.Json.Required.Always)]
        public SentisModelArtifactLocationOpsetVersion OpsetVersion { get; set; }

        [Newtonsoft.Json.JsonProperty("output", Required = Newtonsoft.Json.Required.Always)]
        public ModelOutput Output { get; set; } = new ModelOutput();

        [Newtonsoft.Json.JsonProperty("path", Required = Newtonsoft.Json.Required.Always)]
        public string Path { get; set; }

        [Newtonsoft.Json.JsonProperty("sha256", Required = Newtonsoft.Json.Required.Always)]
        public string Sha256 { get; set; }

        [Newtonsoft.Json.JsonProperty("size_bytes", Required = Newtonsoft.Json.Required.Always)]
        public int SizeBytes { get; set; }

        [Newtonsoft.Json.JsonProperty("storage", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ArtifactStorage Storage { get; set; }

        [Newtonsoft.Json.JsonProperty("target", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public SentisModelArtifactLocationTarget Target { get; set; }

    }

    /// <summary>
    /// A positive x/z footprint size in meters.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Size2D
    {

        [Newtonsoft.Json.JsonProperty("x", Required = Newtonsoft.Json.Required.Always)]
        public double X { get; set; }

        [Newtonsoft.Json.JsonProperty("z", Required = Newtonsoft.Json.Required.Always)]
        public double Z { get; set; }

    }

    /// <summary>
    /// A fixed obstacle in the scenario.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class StaticObstacle
    {

        [Newtonsoft.Json.JsonProperty("center", Required = Newtonsoft.Json.Required.Always)]
        public Position2D Center { get; set; } = new Position2D();

        [Newtonsoft.Json.JsonProperty("height", Required = Newtonsoft.Json.Required.Always)]
        public double Height { get; set; }

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; }

        [Newtonsoft.Json.JsonProperty("rotation_y_degrees", Required = Newtonsoft.Json.Required.Always)]
        public double RotationYDegrees { get; set; }

        [Newtonsoft.Json.JsonProperty("shape", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public StaticObstacleShape Shape { get; set; }

        [Newtonsoft.Json.JsonProperty("size", Required = Newtonsoft.Json.Required.Always)]
        public Size2D Size { get; set; } = new Size2D();

    }

    /// <summary>
    /// A fixed wall segment in the scenario.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class StaticWall
    {

        [Newtonsoft.Json.JsonProperty("center", Required = Newtonsoft.Json.Required.Always)]
        public Position2D Center { get; set; } = new Position2D();

        [Newtonsoft.Json.JsonProperty("height", Required = Newtonsoft.Json.Required.Always)]
        public double Height { get; set; }

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; }

        [Newtonsoft.Json.JsonProperty("rotation_y_degrees", Required = Newtonsoft.Json.Required.Always)]
        public double RotationYDegrees { get; set; }

        [Newtonsoft.Json.JsonProperty("size", Required = Newtonsoft.Json.Required.Always)]
        public Size2D Size { get; set; } = new Size2D();

    }

    /// <summary>
    /// Response returned after accepting a new submission.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class SubmissionResponse
    {

        [Newtonsoft.Json.JsonProperty("cancel_token", Required = Newtonsoft.Json.Required.Always)]
        public string CancelToken { get; set; }

        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public SubmissionResponseStatus Status { get; set; }

        [Newtonsoft.Json.JsonProperty("submission_id", Required = Newtonsoft.Json.Required.Always)]
        public string SubmissionId { get; set; }

    }

    /// <summary>
    /// Terminal reward paid when the task succeeds.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class TerminalRewardComponent : RewardComponent
    {

    }

    /// <summary>
    /// One stochastic training Replay chunk.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class TrainReplayBundleChunk : ReplayBundleChunk
    {

        [Newtonsoft.Json.JsonProperty("avg_reward", Required = Newtonsoft.Json.Required.AllowNull)]
        public object AvgReward { get; set; }

        [Newtonsoft.Json.JsonProperty("avg_steps", Required = Newtonsoft.Json.Required.AllowNull)]
        public object AvgSteps { get; set; }

        [Newtonsoft.Json.JsonProperty("end_step", Required = Newtonsoft.Json.Required.Always)]
        public int EndStep { get; set; }

        [Newtonsoft.Json.JsonProperty("episode_count", Required = Newtonsoft.Json.Required.AllowNull)]
        public object EpisodeCount { get; set; }

        [Newtonsoft.Json.JsonProperty("format", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public TrainReplayBundleChunkFormat Format { get; set; }

        [Newtonsoft.Json.JsonProperty("path", Required = Newtonsoft.Json.Required.Always)]
        public string Path { get; set; }

        [Newtonsoft.Json.JsonProperty("policy_mode", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public TrainReplayBundleChunkPolicyMode PolicyMode { get; set; }

        [Newtonsoft.Json.JsonProperty("start_step", Required = Newtonsoft.Json.Required.Always)]
        public int StartStep { get; set; }

        [Newtonsoft.Json.JsonProperty("step_count", Required = Newtonsoft.Json.Required.Always)]
        public int StepCount { get; set; }

        [Newtonsoft.Json.JsonProperty("success_rate", Required = Newtonsoft.Json.Required.AllowNull)]
        public object SuccessRate { get; set; }

    }

    /// <summary>
    /// Supported training algorithms for scenario bundles.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum TrainingAlgorithm
    {

        [System.Runtime.Serialization.EnumMember(Value = @"ppo")]
        Ppo = 0,


    }

    /// <summary>
    /// Training devices supported by the current Cloud Run runtime.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum TrainingDevice
    {

        [System.Runtime.Serialization.EnumMember(Value = @"cpu")]
        Cpu = 0,


    }

    /// <summary>
    /// Training request parameters for scenario bundles.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class TrainingSpec
    {

        [Newtonsoft.Json.JsonProperty("algorithm", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public TrainingAlgorithm Algorithm { get; set; }

        [Newtonsoft.Json.JsonProperty("batch_size", Required = Newtonsoft.Json.Required.Always)]
        public int BatchSize { get; set; }

        [Newtonsoft.Json.JsonProperty("clip_range", Required = Newtonsoft.Json.Required.Always)]
        public double ClipRange { get; set; }

        [Newtonsoft.Json.JsonProperty("clip_range_vf", Required = Newtonsoft.Json.Required.AllowNull)]
        public double? ClipRangeVf { get; set; }

        [Newtonsoft.Json.JsonProperty("cpu_count", Required = Newtonsoft.Json.Required.AllowNull)]
        public int? CpuCount { get; set; }

        [Newtonsoft.Json.JsonProperty("device", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public TrainingDevice Device { get; set; }

        [Newtonsoft.Json.JsonProperty("ent_coef", Required = Newtonsoft.Json.Required.Always)]
        public double EntCoef { get; set; }

        [Newtonsoft.Json.JsonProperty("eval_episodes", Required = Newtonsoft.Json.Required.Always)]
        public int EvalEpisodes { get; set; }

        [Newtonsoft.Json.JsonProperty("gae_lambda", Required = Newtonsoft.Json.Required.Always)]
        public double GaeLambda { get; set; }

        [Newtonsoft.Json.JsonProperty("gamma", Required = Newtonsoft.Json.Required.Always)]
        public double Gamma { get; set; }

        [Newtonsoft.Json.JsonProperty("learning_rate", Required = Newtonsoft.Json.Required.Always)]
        public double LearningRate { get; set; }

        [Newtonsoft.Json.JsonProperty("max_episode_steps", Required = Newtonsoft.Json.Required.Always)]
        public int MaxEpisodeSteps { get; set; }

        [Newtonsoft.Json.JsonProperty("max_grad_norm", Required = Newtonsoft.Json.Required.Always)]
        public double MaxGradNorm { get; set; }

        [Newtonsoft.Json.JsonProperty("n_envs", Required = Newtonsoft.Json.Required.Always)]
        public int NEnvs { get; set; }

        [Newtonsoft.Json.JsonProperty("n_epochs", Required = Newtonsoft.Json.Required.Always)]
        public int NEpochs { get; set; }

        [Newtonsoft.Json.JsonProperty("n_steps", Required = Newtonsoft.Json.Required.Always)]
        public int NSteps { get; set; }

        [Newtonsoft.Json.JsonProperty("normalize_advantage", Required = Newtonsoft.Json.Required.Always)]
        public bool NormalizeAdvantage { get; set; }

        [Newtonsoft.Json.JsonProperty("randomize_start", Required = Newtonsoft.Json.Required.Always)]
        public bool RandomizeStart { get; set; }

        [Newtonsoft.Json.JsonProperty("replay_eval_interval_steps", Required = Newtonsoft.Json.Required.Always)]
        public int ReplayEvalIntervalSteps { get; set; }

        [Newtonsoft.Json.JsonProperty("replay_train_chunk_steps", Required = Newtonsoft.Json.Required.Always)]
        public int ReplayTrainChunkSteps { get; set; }

        [Newtonsoft.Json.JsonProperty("sde_sample_freq", Required = Newtonsoft.Json.Required.Always)]
        public int SdeSampleFreq { get; set; }

        [Newtonsoft.Json.JsonProperty("seed", Required = Newtonsoft.Json.Required.Always)]
        public long Seed { get; set; }

        [Newtonsoft.Json.JsonProperty("stats_window_size", Required = Newtonsoft.Json.Required.Always)]
        public int StatsWindowSize { get; set; }

        [Newtonsoft.Json.JsonProperty("target_kl", Required = Newtonsoft.Json.Required.AllowNull)]
        public double? TargetKl { get; set; }

        [Newtonsoft.Json.JsonProperty("timesteps", Required = Newtonsoft.Json.Required.Always)]
        public int Timesteps { get; set; }

        [Newtonsoft.Json.JsonProperty("torch_num_threads", Required = Newtonsoft.Json.Required.AllowNull)]
        public int? TorchNumThreads { get; set; }

        [Newtonsoft.Json.JsonProperty("use_sde", Required = Newtonsoft.Json.Required.Always)]
        public bool UseSde { get; set; }

        [Newtonsoft.Json.JsonProperty("vf_coef", Required = Newtonsoft.Json.Required.Always)]
        public double VfCoef { get; set; }

    }

    /// <summary>
    /// High-level metrics from a completed training run.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class TrainingSummary
    {

        [Newtonsoft.Json.JsonProperty("average_episode_reward", Required = Newtonsoft.Json.Required.AllowNull)]
        public double? AverageEpisodeReward { get; set; }

        [Newtonsoft.Json.JsonProperty("average_episode_steps", Required = Newtonsoft.Json.Required.AllowNull)]
        public double? AverageEpisodeSteps { get; set; }

        [Newtonsoft.Json.JsonProperty("configuration", Required = Newtonsoft.Json.Required.Always)]
        public ResolvedTrainingConfig Configuration { get; set; } = new ResolvedTrainingConfig();

        [Newtonsoft.Json.JsonProperty("success_rate", Required = Newtonsoft.Json.Required.AllowNull)]
        public double? SuccessRate { get; set; }

    }

    /// <summary>
    /// Static world geometry for the current scenario contract.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class WorldSpec
    {

        [Newtonsoft.Json.JsonProperty("bounds", Required = Newtonsoft.Json.Required.Always)]
        public Bounds2D Bounds { get; set; } = new Bounds2D();

        [Newtonsoft.Json.JsonProperty("coordinate_system", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public CoordinateSystem CoordinateSystem { get; set; }

        [Newtonsoft.Json.JsonProperty("goal", Required = Newtonsoft.Json.Required.Always)]
        public GoalSpec Goal { get; set; } = new GoalSpec();

        [Newtonsoft.Json.JsonProperty("static_obstacles", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<StaticObstacle> StaticObstacles { get; set; } = new System.Collections.ObjectModel.Collection<StaticObstacle>();

        [Newtonsoft.Json.JsonProperty("static_walls", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.ICollection<StaticWall> StaticWalls { get; set; } = new System.Collections.ObjectModel.Collection<StaticWall>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum Layout
    {

        [System.Runtime.Serialization.EnumMember(Value = @"forward")]
        Forward = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"turn")]
        Turn = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ArtifactLocationFormat
    {

        [System.Runtime.Serialization.EnumMember(Value = @"json")]
        Json = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum EvalReplayBundleChunkFormat
    {

        [System.Runtime.Serialization.EnumMember(Value = @"jsonl.gz")]
        JsonlGz = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum EvalReplayBundleChunkPolicyMode
    {

        [System.Runtime.Serialization.EnumMember(Value = @"deterministic")]
        Deterministic = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum Values
    {

        [System.Runtime.Serialization.EnumMember(Value = @"goal_angle_degrees")]
        GoalAngleDegrees = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"goal_distance_meters")]
        GoalDistanceMeters = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum OnnxModelArtifactLocationFormat
    {

        [System.Runtime.Serialization.EnumMember(Value = @"onnx")]
        Onnx = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum OnnxModelArtifactLocationOpsetVersion
    {

        _17 = 17,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum OnnxModelArtifactLocationTarget
    {

        [System.Runtime.Serialization.EnumMember(Value = @"onnx-runtime")]
        OnnxRuntime = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ReplayBundleManifestSchemaVersion
    {

        [System.Runtime.Serialization.EnumMember(Value = @"replay-bundle.v0")]
        ReplayBundleV0 = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ReplayLogStepPhase
    {

        [System.Runtime.Serialization.EnumMember(Value = @"train")]
        Train = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"eval")]
        Eval = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ReplayLogStepPolicyMode
    {

        [System.Runtime.Serialization.EnumMember(Value = @"stochastic")]
        Stochastic = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"deterministic")]
        Deterministic = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ReplayLogStepSchemaVersion
    {

        [System.Runtime.Serialization.EnumMember(Value = @"replay-log.v0")]
        ReplayLogV0 = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ResolvedTrainingConfigAlgorithm
    {

        [System.Runtime.Serialization.EnumMember(Value = @"ppo")]
        Ppo = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ResolvedTrainingConfigDevice
    {

        [System.Runtime.Serialization.EnumMember(Value = @"cpu")]
        Cpu = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ResolvedTrainingConfigLibrary
    {

        [System.Runtime.Serialization.EnumMember(Value = @"stable-baselines3")]
        StableBaselines3 = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ResultBundleSchemaVersion
    {

        [System.Runtime.Serialization.EnumMember(Value = @"result-bundle.v0")]
        ResultBundleV0 = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ResultBundleStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"completed")]
        Completed = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"failed")]
        Failed = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ScenarioBundleSchemaVersion
    {

        [System.Runtime.Serialization.EnumMember(Value = @"scenario-bundle.v0")]
        ScenarioBundleV0 = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SentisModelArtifactLocationFormat
    {

        [System.Runtime.Serialization.EnumMember(Value = @"onnx")]
        Onnx = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SentisModelArtifactLocationOpsetVersion
    {

        _15 = 15,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SentisModelArtifactLocationTarget
    {

        [System.Runtime.Serialization.EnumMember(Value = @"unity-sentis")]
        UnitySentis = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum StaticObstacleShape
    {

        [System.Runtime.Serialization.EnumMember(Value = @"box")]
        Box = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SubmissionResponseStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"accepted")]
        Accepted = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum TrainReplayBundleChunkFormat
    {

        [System.Runtime.Serialization.EnumMember(Value = @"jsonl.gz")]
        JsonlGz = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum TrainReplayBundleChunkPolicyMode
    {

        [System.Runtime.Serialization.EnumMember(Value = @"stochastic")]
        Stochastic = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Interface, AllowMultiple = true)]
    internal class JsonInheritanceAttribute : System.Attribute
    {
        public JsonInheritanceAttribute(string key, System.Type type)
        {
            Key = key;
            Type = type;
        }

        public string Key { get; }

        public System.Type Type { get; }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public class JsonInheritanceConverter : Newtonsoft.Json.JsonConverter
    {
        internal static readonly string DefaultDiscriminatorName = "discriminator";

        private readonly string _discriminatorName;

        [System.ThreadStatic]
        private static bool _isReading;

        [System.ThreadStatic]
        private static bool _isWriting;

        public JsonInheritanceConverter()
        {
            _discriminatorName = DefaultDiscriminatorName;
        }

        public JsonInheritanceConverter(string discriminatorName)
        {
            _discriminatorName = discriminatorName;
        }

        public string DiscriminatorName { get { return _discriminatorName; } }

        public override void WriteJson(Newtonsoft.Json.JsonWriter writer, object value, Newtonsoft.Json.JsonSerializer serializer)
        {
            try
            {
                _isWriting = true;

                var jObject = Newtonsoft.Json.Linq.JObject.FromObject(value, serializer);
                jObject.AddFirst(new Newtonsoft.Json.Linq.JProperty(_discriminatorName, GetSubtypeDiscriminator(value.GetType())));
                writer.WriteToken(jObject.CreateReader());
            }
            finally
            {
                _isWriting = false;
            }
        }

        public override bool CanWrite
        {
            get
            {
                if (_isWriting)
                {
                    _isWriting = false;
                    return false;
                }
                return true;
            }
        }

        public override bool CanRead
        {
            get
            {
                if (_isReading)
                {
                    _isReading = false;
                    return false;
                }
                return true;
            }
        }

        public override bool CanConvert(System.Type objectType)
        {
            return true;
        }

        public override object ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer)
        {
            var jObject = serializer.Deserialize<Newtonsoft.Json.Linq.JObject>(reader);
            if (jObject == null)
                return null;

            var discriminatorValue = jObject.GetValue(_discriminatorName);
            var discriminator = discriminatorValue != null ? Newtonsoft.Json.Linq.Extensions.Value<string>(discriminatorValue) : null;
            var subtype = GetObjectSubtype(objectType, discriminator);

            var objectContract = serializer.ContractResolver.ResolveContract(subtype) as Newtonsoft.Json.Serialization.JsonObjectContract;
            if (objectContract == null || System.Linq.Enumerable.All(objectContract.Properties, p => p.PropertyName != _discriminatorName))
            {
                jObject.Remove(_discriminatorName);
            }

            try
            {
                _isReading = true;
                return serializer.Deserialize(jObject.CreateReader(), subtype);
            }
            finally
            {
                _isReading = false;
            }
        }

        private System.Type GetObjectSubtype(System.Type objectType, string discriminator)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Key == discriminator)
                    return attribute.Type;
            }

            return objectType;
        }

        private string GetSubtypeDiscriminator(System.Type objectType)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Type == objectType)
                    return attribute.Key;
            }

            return objectType.Name;
        }
    }
}
