//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace EmbodiedLab.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Robot action layout expected by the policy.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ActionSpace
    {

        [Newtonsoft.Json.JsonProperty("layout", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore, ItemConverterType = typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public System.Collections.Generic.ICollection<Layout> Layout { get; set; }

        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ActionSpaceType Type { get; set; } = EmbodiedLab.Contracts.ActionSpaceType.Continuous;

    }

    /// <summary>
    /// Supported robot action space families.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ActionSpaceType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"continuous")]
        Continuous = 0,


    }

    /// <summary>
    /// Supported artifact formats.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ArtifactFormat
    {

        [System.Runtime.Serialization.EnumMember(Value = @"onnx")]
        Onnx = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"json")]
        Json = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"jsonl")]
        Jsonl = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"jsonl.gz")]
        JsonlGz = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"zip")]
        Zip = 4,


    }

    /// <summary>
    /// Location and format of a result artifact.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ArtifactLocation
    {

        [Newtonsoft.Json.JsonProperty("bucket", Required = Newtonsoft.Json.Required.Always)]
        public string Bucket { get; set; }

        [Newtonsoft.Json.JsonProperty("format", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ArtifactFormat Format { get; set; }

        [Newtonsoft.Json.JsonProperty("path", Required = Newtonsoft.Json.Required.Always)]
        public string Path { get; set; }

        [Newtonsoft.Json.JsonProperty("storage", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ArtifactStorage Storage { get; set; } = EmbodiedLab.Contracts.ArtifactStorage.Gcs;

    }

    /// <summary>
    /// Supported artifact storage backends.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ArtifactStorage
    {

        [System.Runtime.Serialization.EnumMember(Value = @"gcs")]
        Gcs = 0,


    }

    /// <summary>
    /// Axis-aligned world bounds on the x/z plane.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Bounds2D
    {

        [Newtonsoft.Json.JsonProperty("max", Required = Newtonsoft.Json.Required.Always)]
        public Position2D Max { get; set; } = new Position2D();

        [Newtonsoft.Json.JsonProperty("min", Required = Newtonsoft.Json.Required.Always)]
        public Position2D Min { get; set; } = new Position2D();

    }

    /// <summary>
    /// Reward component emitted on collisions.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class CollisionRewardComponent : RewardComponent
    {

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; }

        [Newtonsoft.Json.JsonProperty("weight", Required = Newtonsoft.Json.Required.Always)]
        public double Weight { get; set; }

    }

    /// <summary>
    /// Compatibility metadata required by EnvForge and EmbodiedLab.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Compatibility
    {

        [Newtonsoft.Json.JsonProperty("envforge_min_version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string EnvforgeMinVersion { get; set; } = "0.1.0";

        [Newtonsoft.Json.JsonProperty("robot_version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string RobotVersion { get; set; } = "simple_robot.v1";

        [Newtonsoft.Json.JsonProperty("sensor_version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SensorVersion { get; set; } = "basic_sensors.v0";

    }

    /// <summary>
    /// Supported world coordinate systems for scenario bundles.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum CoordinateSystem
    {

        [System.Runtime.Serialization.EnumMember(Value = @"envforge_xz_meters")]
        EnvforgeXzMeters = 0,


    }

    /// <summary>
    /// Metadata about the tool that created a scenario bundle.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class CreatedBy
    {

        [Newtonsoft.Json.JsonProperty("tool", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Tool { get; set; } = "EnvForge";

        [Newtonsoft.Json.JsonProperty("version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Version { get; set; } = "0.1.0";

    }

    /// <summary>
    /// Reward based on distance progress toward a target object.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class DistanceDeltaRewardComponent : RewardComponent
    {

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; }

        [Newtonsoft.Json.JsonProperty("target", Required = Newtonsoft.Json.Required.Always)]
        public string Target { get; set; }

        [Newtonsoft.Json.JsonProperty("weight", Required = Newtonsoft.Json.Required.Always)]
        public double Weight { get; set; }

    }

    /// <summary>
    /// Forward distance sensor configuration.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class DistanceSensor : SensorSpec
    {

        [Newtonsoft.Json.JsonProperty("direction", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public SensorDirection Direction { get; set; } = EmbodiedLab.Contracts.SensorDirection.Forward;

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; }

        [Newtonsoft.Json.JsonProperty("range_meters", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double RangeMeters { get; set; } = 5D;

    }

    /// <summary>
    /// Structured failure details for failed result bundles.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ErrorReport
    {

        [Newtonsoft.Json.JsonProperty("details", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Details { get; set; }

        [Newtonsoft.Json.JsonProperty("message", Required = Newtonsoft.Json.Required.Always)]
        public string Message { get; set; }

    }

    /// <summary>
    /// Forward semantic camera sensor configuration.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ForwardCameraSensor : SensorSpec
    {

        [Newtonsoft.Json.JsonProperty("far_clip_meters", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double FarClipMeters { get; set; } = 100D;

        [Newtonsoft.Json.JsonProperty("height", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Height { get; set; } = 84;

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; }

        [Newtonsoft.Json.JsonProperty("mount_height_max_meters", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? MountHeightMaxMeters { get; set; }

        [Newtonsoft.Json.JsonProperty("mount_height_meters", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double MountHeightMeters { get; set; } = 0.6D;

        [Newtonsoft.Json.JsonProperty("mount_height_min_meters", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? MountHeightMinMeters { get; set; }

        [Newtonsoft.Json.JsonProperty("near_clip_meters", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double NearClipMeters { get; set; } = 0.05D;

        [Newtonsoft.Json.JsonProperty("pitch_degrees", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double PitchDegrees { get; set; } = 0D;

        [Newtonsoft.Json.JsonProperty("semantic_mode", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public SemanticMode SemanticMode { get; set; } = EmbodiedLab.Contracts.SemanticMode.TraversableVsBlocked;

        [Newtonsoft.Json.JsonProperty("vertical_fov_degrees", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double VerticalFovDegrees { get; set; } = 70D;

        [Newtonsoft.Json.JsonProperty("width", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Width { get; set; } = 112;

    }

    /// <summary>
    /// Goal region used for navigation training.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GoalSpec
    {

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; }

        [Newtonsoft.Json.JsonProperty("position", Required = Newtonsoft.Json.Required.Always)]
        public Position2D Position { get; set; } = new Position2D();

        [Newtonsoft.Json.JsonProperty("radius", Required = Newtonsoft.Json.Required.Always)]
        public double Radius { get; set; }

    }

    /// <summary>
    /// Model artifact location with Unity compatibility metadata.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ModelArtifactLocation
    {

        [Newtonsoft.Json.JsonProperty("bucket", Required = Newtonsoft.Json.Required.Always)]
        public string Bucket { get; set; }

        [Newtonsoft.Json.JsonProperty("format", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ArtifactFormat Format { get; set; }

        [Newtonsoft.Json.JsonProperty("input", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ModelInput Input { get; set; }

        [Newtonsoft.Json.JsonProperty("opset_version", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? OpsetVersion { get; set; }

        [Newtonsoft.Json.JsonProperty("output", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ModelOutput Output { get; set; }

        [Newtonsoft.Json.JsonProperty("path", Required = Newtonsoft.Json.Required.Always)]
        public string Path { get; set; }

        [Newtonsoft.Json.JsonProperty("storage", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ArtifactStorage Storage { get; set; } = EmbodiedLab.Contracts.ArtifactStorage.Gcs;

        [Newtonsoft.Json.JsonProperty("target", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Target { get; set; }

    }

    /// <summary>
    /// Input metadata for an EnvForge-loadable model artifact.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ModelInput
    {

        [Newtonsoft.Json.JsonProperty("dtype", Required = Newtonsoft.Json.Required.Always)]
        public string Dtype { get; set; }

        [Newtonsoft.Json.JsonProperty("layout", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string> Layout { get; set; }

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; }

        [Newtonsoft.Json.JsonProperty("shape", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<int> Shape { get; set; }

    }

    /// <summary>
    /// Output metadata for an EnvForge-loadable model artifact.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ModelOutput
    {

        [Newtonsoft.Json.JsonProperty("action_mapping", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IDictionary<string, string> ActionMapping { get; set; }

        [Newtonsoft.Json.JsonProperty("layout", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string> Layout { get; set; }

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; }

    }

    /// <summary>
    /// Reward component emitted at each simulation step.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class PerStepRewardComponent : RewardComponent
    {

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; }

        [Newtonsoft.Json.JsonProperty("weight", Required = Newtonsoft.Json.Required.Always)]
        public double Weight { get; set; }

    }

    /// <summary>
    /// Robot pose on the x/z plane.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Pose2D
    {

        [Newtonsoft.Json.JsonProperty("position", Required = Newtonsoft.Json.Required.Always)]
        public Position2D Position { get; set; } = new Position2D();

        [Newtonsoft.Json.JsonProperty("rotation_y_degrees", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double RotationYDegrees { get; set; } = 0D;

    }

    /// <summary>
    /// A point on the EnvForge horizontal x/z plane.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Position2D
    {

        [Newtonsoft.Json.JsonProperty("x", Required = Newtonsoft.Json.Required.Always)]
        public double X { get; set; }

        [Newtonsoft.Json.JsonProperty("z", Required = Newtonsoft.Json.Required.Always)]
        public double Z { get; set; }

    }

    /// <summary>
    /// Training progress snapshot stored in each result document.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Progress
    {

        [Newtonsoft.Json.JsonProperty("current_step", Required = Newtonsoft.Json.Required.Always)]
        public int CurrentStep { get; set; }

        [Newtonsoft.Json.JsonProperty("message", Required = Newtonsoft.Json.Required.Always)]
        public string Message { get; set; }

        [Newtonsoft.Json.JsonProperty("phase", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ResultStatus Phase { get; set; }

        [Newtonsoft.Json.JsonProperty("total_steps", Required = Newtonsoft.Json.Required.Always)]
        public int TotalSteps { get; set; }

    }

    /// <summary>
    /// Action values emitted for a replay step.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayAction
    {

        [Newtonsoft.Json.JsonProperty("values", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<ReplayNamedValue> Values { get; set; }

    }

    /// <summary>
    /// One compressed train or evaluation chunk in a Replay Bundle.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayBundleChunk
    {

        [Newtonsoft.Json.JsonProperty("avg_reward", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? AvgReward { get; set; }

        [Newtonsoft.Json.JsonProperty("avg_steps", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? AvgSteps { get; set; }

        [Newtonsoft.Json.JsonProperty("checkpoint_step", Required = Newtonsoft.Json.Required.Always)]
        public int CheckpointStep { get; set; }

        [Newtonsoft.Json.JsonProperty("end_step", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? EndStep { get; set; }

        [Newtonsoft.Json.JsonProperty("episode_count", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? EpisodeCount { get; set; }

        [Newtonsoft.Json.JsonProperty("format", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ReplayBundleChunkFormat Format { get; set; }

        [Newtonsoft.Json.JsonProperty("path", Required = Newtonsoft.Json.Required.Always)]
        public string Path { get; set; }

        [Newtonsoft.Json.JsonProperty("phase", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ReplayBundleChunkPhase Phase { get; set; }

        [Newtonsoft.Json.JsonProperty("policy_mode", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ReplayBundleChunkPolicyMode PolicyMode { get; set; }

        [Newtonsoft.Json.JsonProperty("start_step", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? StartStep { get; set; }

        [Newtonsoft.Json.JsonProperty("step_count", Required = Newtonsoft.Json.Required.Always)]
        public int StepCount { get; set; }

        [Newtonsoft.Json.JsonProperty("success_rate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? SuccessRate { get; set; }

    }

    /// <summary>
    /// Manifest describing the chunks in one Replay Bundle.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayBundleManifest
    {

        [Newtonsoft.Json.JsonProperty("chunks", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<ReplayBundleChunk> Chunks { get; set; }

        [Newtonsoft.Json.JsonProperty("job_id", Required = Newtonsoft.Json.Required.Always)]
        public string JobId { get; set; }

        [Newtonsoft.Json.JsonProperty("scenario_id", Required = Newtonsoft.Json.Required.Always)]
        public string ScenarioId { get; set; }

        [Newtonsoft.Json.JsonProperty("schema_version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ReplayBundleManifestSchemaVersion SchemaVersion { get; set; } = EmbodiedLab.Contracts.ReplayBundleManifestSchemaVersion.ReplayBundleV0;

        [Newtonsoft.Json.JsonProperty("total_timesteps", Required = Newtonsoft.Json.Required.Always)]
        public int TotalTimesteps { get; set; }

    }

    /// <summary>
    /// A compact event emitted during replay.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayEvent
    {

        [Newtonsoft.Json.JsonProperty("message", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Message { get; set; }

        [Newtonsoft.Json.JsonProperty("object_id", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ObjectId { get; set; }

        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; set; }

    }

    /// <summary>
    /// One JSON Lines row in an EnvForge replay log.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayLogStep
    {

        [Newtonsoft.Json.JsonProperty("action", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ReplayAction Action { get; set; }

        [Newtonsoft.Json.JsonProperty("checkpoint_step", Required = Newtonsoft.Json.Required.Always)]
        public int CheckpointStep { get; set; }

        [Newtonsoft.Json.JsonProperty("env_index", Required = Newtonsoft.Json.Required.Always)]
        public int EnvIndex { get; set; }

        [Newtonsoft.Json.JsonProperty("episode_id", Required = Newtonsoft.Json.Required.Always)]
        public string EpisodeId { get; set; }

        [Newtonsoft.Json.JsonProperty("events", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<ReplayEvent> Events { get; set; }

        [Newtonsoft.Json.JsonProperty("job_id", Required = Newtonsoft.Json.Required.Always)]
        public string JobId { get; set; }

        [Newtonsoft.Json.JsonProperty("phase", Required = Newtonsoft.Json.Required.Always)]
        public string Phase { get; set; }

        [Newtonsoft.Json.JsonProperty("policy_mode", Required = Newtonsoft.Json.Required.Always)]
        public string PolicyMode { get; set; }

        [Newtonsoft.Json.JsonProperty("reward", Required = Newtonsoft.Json.Required.Always)]
        public ReplayReward Reward { get; set; } = new ReplayReward();

        [Newtonsoft.Json.JsonProperty("robot", Required = Newtonsoft.Json.Required.Always)]
        public ReplayRobotState Robot { get; set; } = new ReplayRobotState();

        [Newtonsoft.Json.JsonProperty("scenario_id", Required = Newtonsoft.Json.Required.Always)]
        public string ScenarioId { get; set; }

        [Newtonsoft.Json.JsonProperty("schema_version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ReplayLogStepSchemaVersion SchemaVersion { get; set; } = EmbodiedLab.Contracts.ReplayLogStepSchemaVersion.ReplayLogV0;

        [Newtonsoft.Json.JsonProperty("sensors", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<ReplaySensorSummary> Sensors { get; set; }

        [Newtonsoft.Json.JsonProperty("step_index", Required = Newtonsoft.Json.Required.Always)]
        public int StepIndex { get; set; }

        [Newtonsoft.Json.JsonProperty("terminated", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool Terminated { get; set; } = false;

        [Newtonsoft.Json.JsonProperty("termination_reason", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string TerminationReason { get; set; }

        [Newtonsoft.Json.JsonProperty("time_seconds", Required = Newtonsoft.Json.Required.Always)]
        public double TimeSeconds { get; set; }

    }

    /// <summary>
    /// A named scalar value in a JsonUtility-friendly replay payload.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayNamedValue
    {

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; }

        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.Always)]
        public double Value { get; set; }

    }

    /// <summary>
    /// A continuous replay position on the x/z plane.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayPosition
    {

        [Newtonsoft.Json.JsonProperty("x", Required = Newtonsoft.Json.Required.Always)]
        public double X { get; set; }

        [Newtonsoft.Json.JsonProperty("z", Required = Newtonsoft.Json.Required.Always)]
        public double Z { get; set; }

    }

    /// <summary>
    /// Reward values emitted for a replay step.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayReward
    {

        [Newtonsoft.Json.JsonProperty("components", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<ReplayNamedValue> Components { get; set; }

        [Newtonsoft.Json.JsonProperty("total", Required = Newtonsoft.Json.Required.Always)]
        public double Total { get; set; }

    }

    /// <summary>
    /// Robot state emitted in a replay step.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplayRobotState
    {

        [Newtonsoft.Json.JsonProperty("position", Required = Newtonsoft.Json.Required.Always)]
        public ReplayPosition Position { get; set; } = new ReplayPosition();

        [Newtonsoft.Json.JsonProperty("rotation_y_degrees", Required = Newtonsoft.Json.Required.Always)]
        public double RotationYDegrees { get; set; }

    }

    /// <summary>
    /// A compact sensor summary emitted during replay.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReplaySensorSummary
    {

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; }

        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; set; }

        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.Always)]
        public double Value { get; set; }

    }

    /// <summary>
    /// Artifacts produced by a training run.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ResultArtifacts
    {

        [Newtonsoft.Json.JsonProperty("model", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ArtifactLocation Model { get; set; }

        [Newtonsoft.Json.JsonProperty("onnx_model", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ArtifactLocation OnnxModel { get; set; }

        [Newtonsoft.Json.JsonProperty("replay_bundle", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ArtifactLocation ReplayBundle { get; set; }

        [Newtonsoft.Json.JsonProperty("sentis_model", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ModelArtifactLocation SentisModel { get; set; }

    }

    /// <summary>
    /// EnvForge-facing training result bundle.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ResultBundle
    {

        [Newtonsoft.Json.JsonProperty("artifacts", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ResultArtifacts Artifacts { get; set; }

        [Newtonsoft.Json.JsonProperty("compatibility", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ResultCompatibility Compatibility { get; set; }

        [Newtonsoft.Json.JsonProperty("error", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ErrorReport Error { get; set; }

        [Newtonsoft.Json.JsonProperty("job_id", Required = Newtonsoft.Json.Required.Always)]
        public string JobId { get; set; }

        [Newtonsoft.Json.JsonProperty("scenario_id", Required = Newtonsoft.Json.Required.Always)]
        public string ScenarioId { get; set; }

        [Newtonsoft.Json.JsonProperty("schema_version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ResultBundleSchemaVersion SchemaVersion { get; set; } = EmbodiedLab.Contracts.ResultBundleSchemaVersion.ResultBundleV0;

        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ResultStatus Status { get; set; }

        [Newtonsoft.Json.JsonProperty("summary", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public TrainingSummary Summary { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Compatibility metadata needed by EnvForge when loading a result.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ResultCompatibility
    {

        [Newtonsoft.Json.JsonProperty("action_layout", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string> ActionLayout { get; set; }

        [Newtonsoft.Json.JsonProperty("envforge_min_version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string EnvforgeMinVersion { get; set; } = "0.1.0";

        [Newtonsoft.Json.JsonProperty("observation_layout", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string> ObservationLayout { get; set; }

        [Newtonsoft.Json.JsonProperty("robot_version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string RobotVersion { get; set; } = "simple_robot.v1";

        [Newtonsoft.Json.JsonProperty("scenario_schema_version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ScenarioSchemaVersion { get; set; } = "scenario-bundle.v0";

        [Newtonsoft.Json.JsonProperty("sensor_version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SensorVersion { get; set; } = "basic_sensors.v0";

    }

    /// <summary>
    /// Full result document written to Firestore.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ResultDocument
    {

        [Newtonsoft.Json.JsonProperty("error", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Error { get; set; }

        [Newtonsoft.Json.JsonProperty("progress", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Progress Progress { get; set; }

        [Newtonsoft.Json.JsonProperty("result_bundle", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ResultBundle ResultBundle { get; set; }

        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ResultStatus Status { get; set; }

        [Newtonsoft.Json.JsonProperty("submission_id", Required = Newtonsoft.Json.Required.Always)]
        public string SubmissionId { get; set; }

        [Newtonsoft.Json.JsonProperty("summary", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public object Summary { get; set; }

        [Newtonsoft.Json.JsonProperty("updated_at", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string UpdatedAt { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Lifecycle states of a training result.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ResultStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"queued")]
        Queued = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"starting")]
        Starting = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"running")]
        Running = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"cancelling")]
        Cancelling = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"cancelled")]
        Cancelled = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"completed")]
        Completed = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"failed")]
        Failed = 6,


    }

    [Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "type")]
    [JsonInheritanceAttribute("collision", typeof(CollisionRewardComponent))]
    [JsonInheritanceAttribute("distance_delta", typeof(DistanceDeltaRewardComponent))]
    [JsonInheritanceAttribute("per_step", typeof(PerStepRewardComponent))]
    [JsonInheritanceAttribute("terminal_reward", typeof(TerminalRewardComponent))]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public abstract partial class RewardComponent
    {

    }

    /// <summary>
    /// Declarative reward configuration for training.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class RewardSpec
    {

        [Newtonsoft.Json.JsonProperty("components", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<RewardComponent> Components { get; set; }

    }

    /// <summary>
    /// Robot descriptor for an EnvForge scenario.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class RobotSpec
    {

        [Newtonsoft.Json.JsonProperty("action_space", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ActionSpace ActionSpace { get; set; }

        [Newtonsoft.Json.JsonProperty("radius", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double Radius { get; set; } = 0.45D;

        [Newtonsoft.Json.JsonProperty("start_pose", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Pose2D StartPose { get; set; }

        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public RobotType Type { get; set; } = EmbodiedLab.Contracts.RobotType.SimpleRobot;

    }

    /// <summary>
    /// Robot archetypes supported by the first EnvForge integration.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum RobotType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"simple_robot")]
        SimpleRobot = 0,


    }

    /// <summary>
    /// Top-level request body for POST /submissions.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ScenarioBundle
    {

        [Newtonsoft.Json.JsonProperty("compatibility", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Compatibility Compatibility { get; set; }

        [Newtonsoft.Json.JsonProperty("created_by", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public CreatedBy CreatedBy { get; set; }

        [Newtonsoft.Json.JsonProperty("reward", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public RewardSpec Reward { get; set; }

        [Newtonsoft.Json.JsonProperty("robot", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public RobotSpec Robot { get; set; }

        [Newtonsoft.Json.JsonProperty("scenario_id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ScenarioId { get; set; } = "scenario_demo_001";

        [Newtonsoft.Json.JsonProperty("schema_version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ScenarioBundleSchemaVersion SchemaVersion { get; set; } = EmbodiedLab.Contracts.ScenarioBundleSchemaVersion.ScenarioBundleV0;

        [Newtonsoft.Json.JsonProperty("sensors", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<SensorSpec> Sensors { get; set; }

        [Newtonsoft.Json.JsonProperty("training", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public TrainingSpec Training { get; set; }

        [Newtonsoft.Json.JsonProperty("world", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public WorldSpec World { get; set; }

    }

    /// <summary>
    /// Supported semantic camera encodings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SemanticMode
    {

        [System.Runtime.Serialization.EnumMember(Value = @"traversable_vs_blocked")]
        TraversableVsBlocked = 0,


    }

    /// <summary>
    /// Supported distance sensor directions.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SensorDirection
    {

        [System.Runtime.Serialization.EnumMember(Value = @"forward")]
        Forward = 0,


    }

    [Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "type")]
    [JsonInheritanceAttribute("distance_sensor", typeof(DistanceSensor))]
    [JsonInheritanceAttribute("forward_camera", typeof(ForwardCameraSensor))]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public abstract partial class SensorSpec
    {

    }

    /// <summary>
    /// A positive x/z footprint size in meters.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Size2D
    {

        [Newtonsoft.Json.JsonProperty("x", Required = Newtonsoft.Json.Required.Always)]
        public double X { get; set; }

        [Newtonsoft.Json.JsonProperty("z", Required = Newtonsoft.Json.Required.Always)]
        public double Z { get; set; }

    }

    /// <summary>
    /// A fixed obstacle in the scenario.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class StaticObstacle
    {

        [Newtonsoft.Json.JsonProperty("center", Required = Newtonsoft.Json.Required.Always)]
        public Position2D Center { get; set; } = new Position2D();

        [Newtonsoft.Json.JsonProperty("height", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double Height { get; set; } = 1D;

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; }

        [Newtonsoft.Json.JsonProperty("rotation_y_degrees", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double RotationYDegrees { get; set; } = 0D;

        [Newtonsoft.Json.JsonProperty("shape", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public StaticObstacleShape Shape { get; set; } = EmbodiedLab.Contracts.StaticObstacleShape.Box;

        [Newtonsoft.Json.JsonProperty("size", Required = Newtonsoft.Json.Required.Always)]
        public Size2D Size { get; set; } = new Size2D();

    }

    /// <summary>
    /// A fixed wall segment in the scenario.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class StaticWall
    {

        [Newtonsoft.Json.JsonProperty("center", Required = Newtonsoft.Json.Required.Always)]
        public Position2D Center { get; set; } = new Position2D();

        [Newtonsoft.Json.JsonProperty("height", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double Height { get; set; } = 2D;

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; }

        [Newtonsoft.Json.JsonProperty("rotation_y_degrees", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double RotationYDegrees { get; set; } = 0D;

        [Newtonsoft.Json.JsonProperty("size", Required = Newtonsoft.Json.Required.Always)]
        public Size2D Size { get; set; } = new Size2D();

    }

    /// <summary>
    /// Response returned after accepting a new submission.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class SubmissionResponse
    {

        [Newtonsoft.Json.JsonProperty("cancel_token", Required = Newtonsoft.Json.Required.Always)]
        public string CancelToken { get; set; }

        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public SubmissionResponseStatus Status { get; set; }

        [Newtonsoft.Json.JsonProperty("submission_id", Required = Newtonsoft.Json.Required.Always)]
        public string SubmissionId { get; set; }

    }

    /// <summary>
    /// Terminal reward paid when the task succeeds.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class TerminalRewardComponent : RewardComponent
    {

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; }

        [Newtonsoft.Json.JsonProperty("weight", Required = Newtonsoft.Json.Required.Always)]
        public double Weight { get; set; }

    }

    /// <summary>
    /// Supported training algorithms for EnvForge scenarios.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum TrainingAlgorithm
    {

        [System.Runtime.Serialization.EnumMember(Value = @"ppo")]
        Ppo = 0,


    }

    /// <summary>
    /// Response returned after accepting a training request.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class TrainingResponse
    {

        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public TrainingResponseStatus Status { get; set; }

        [Newtonsoft.Json.JsonProperty("submission_id", Required = Newtonsoft.Json.Required.Always)]
        public string SubmissionId { get; set; }

    }

    /// <summary>
    /// Training request parameters for EnvForge scenario bundles.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class TrainingSpec
    {

        [Newtonsoft.Json.JsonProperty("algorithm", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public TrainingAlgorithm Algorithm { get; set; } = EmbodiedLab.Contracts.TrainingAlgorithm.Ppo;

        [Newtonsoft.Json.JsonProperty("batch_size", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int BatchSize { get; set; } = 32;

        [Newtonsoft.Json.JsonProperty("cpu_count", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? CpuCount { get; set; }

        [Newtonsoft.Json.JsonProperty("ent_coef", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double EntCoef { get; set; } = 0D;

        [Newtonsoft.Json.JsonProperty("eval_episodes", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int EvalEpisodes { get; set; } = 20;

        [Newtonsoft.Json.JsonProperty("gamma", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double Gamma { get; set; } = 0.99D;

        [Newtonsoft.Json.JsonProperty("learning_rate", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double LearningRate { get; set; } = 0.0003D;

        [Newtonsoft.Json.JsonProperty("max_episode_steps", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int MaxEpisodeSteps { get; set; } = 512;

        [Newtonsoft.Json.JsonProperty("n_envs", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int NEnvs { get; set; } = 1;

        [Newtonsoft.Json.JsonProperty("n_epochs", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int NEpochs { get; set; } = 3;

        [Newtonsoft.Json.JsonProperty("n_steps", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int NSteps { get; set; } = 32;

        [Newtonsoft.Json.JsonProperty("seed", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Seed { get; set; } = 10;

        [Newtonsoft.Json.JsonProperty("timesteps", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Timesteps { get; set; } = 5000;

        [Newtonsoft.Json.JsonProperty("torch_num_threads", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? TorchNumThreads { get; set; }

    }

    /// <summary>
    /// High-level metrics from a completed training run.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class TrainingSummary
    {

        [Newtonsoft.Json.JsonProperty("average_episode_reward", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? AverageEpisodeReward { get; set; }

        [Newtonsoft.Json.JsonProperty("average_episode_steps", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? AverageEpisodeSteps { get; set; }

        [Newtonsoft.Json.JsonProperty("success_rate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? SuccessRate { get; set; }

        [Newtonsoft.Json.JsonProperty("training_seed", Required = Newtonsoft.Json.Required.Always)]
        public int TrainingSeed { get; set; }

        [Newtonsoft.Json.JsonProperty("training_timesteps", Required = Newtonsoft.Json.Required.Always)]
        public int TrainingTimesteps { get; set; }

    }

    /// <summary>
    /// Static world geometry for the first EnvForge contract.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class WorldSpec
    {

        [Newtonsoft.Json.JsonProperty("bounds", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Bounds2D Bounds { get; set; }

        [Newtonsoft.Json.JsonProperty("coordinate_system", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public CoordinateSystem CoordinateSystem { get; set; } = EmbodiedLab.Contracts.CoordinateSystem.EnvforgeXzMeters;

        [Newtonsoft.Json.JsonProperty("goal", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public GoalSpec Goal { get; set; }

        [Newtonsoft.Json.JsonProperty("static_obstacles", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<StaticObstacle> StaticObstacles { get; set; }

        [Newtonsoft.Json.JsonProperty("static_walls", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<StaticWall> StaticWalls { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum Layout
    {

        [System.Runtime.Serialization.EnumMember(Value = @"forward")]
        Forward = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"turn")]
        Turn = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ReplayBundleChunkFormat
    {

        [System.Runtime.Serialization.EnumMember(Value = @"jsonl.gz")]
        JsonlGz = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ReplayBundleChunkPhase
    {

        [System.Runtime.Serialization.EnumMember(Value = @"train")]
        Train = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"eval")]
        Eval = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ReplayBundleChunkPolicyMode
    {

        [System.Runtime.Serialization.EnumMember(Value = @"stochastic")]
        Stochastic = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"deterministic")]
        Deterministic = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ReplayBundleManifestSchemaVersion
    {

        [System.Runtime.Serialization.EnumMember(Value = @"replay-bundle.v0")]
        ReplayBundleV0 = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ReplayLogStepSchemaVersion
    {

        [System.Runtime.Serialization.EnumMember(Value = @"replay-log.v0")]
        ReplayLogV0 = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ResultBundleSchemaVersion
    {

        [System.Runtime.Serialization.EnumMember(Value = @"result-bundle.v0")]
        ResultBundleV0 = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ScenarioBundleSchemaVersion
    {

        [System.Runtime.Serialization.EnumMember(Value = @"scenario-bundle.v0")]
        ScenarioBundleV0 = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum StaticObstacleShape
    {

        [System.Runtime.Serialization.EnumMember(Value = @"box")]
        Box = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SubmissionResponseStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"accepted")]
        Accepted = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum TrainingResponseStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"accepted")]
        Accepted = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Interface, AllowMultiple = true)]
    internal class JsonInheritanceAttribute : System.Attribute
    {
        public JsonInheritanceAttribute(string key, System.Type type)
        {
            Key = key;
            Type = type;
        }

        public string Key { get; }

        public System.Type Type { get; }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public class JsonInheritanceConverter : Newtonsoft.Json.JsonConverter
    {
        internal static readonly string DefaultDiscriminatorName = "discriminator";

        private readonly string _discriminatorName;

        [System.ThreadStatic]
        private static bool _isReading;

        [System.ThreadStatic]
        private static bool _isWriting;

        public JsonInheritanceConverter()
        {
            _discriminatorName = DefaultDiscriminatorName;
        }

        public JsonInheritanceConverter(string discriminatorName)
        {
            _discriminatorName = discriminatorName;
        }

        public string DiscriminatorName { get { return _discriminatorName; } }

        public override void WriteJson(Newtonsoft.Json.JsonWriter writer, object value, Newtonsoft.Json.JsonSerializer serializer)
        {
            try
            {
                _isWriting = true;

                var jObject = Newtonsoft.Json.Linq.JObject.FromObject(value, serializer);
                jObject.AddFirst(new Newtonsoft.Json.Linq.JProperty(_discriminatorName, GetSubtypeDiscriminator(value.GetType())));
                writer.WriteToken(jObject.CreateReader());
            }
            finally
            {
                _isWriting = false;
            }
        }

        public override bool CanWrite
        {
            get
            {
                if (_isWriting)
                {
                    _isWriting = false;
                    return false;
                }
                return true;
            }
        }

        public override bool CanRead
        {
            get
            {
                if (_isReading)
                {
                    _isReading = false;
                    return false;
                }
                return true;
            }
        }

        public override bool CanConvert(System.Type objectType)
        {
            return true;
        }

        public override object ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer)
        {
            var jObject = serializer.Deserialize<Newtonsoft.Json.Linq.JObject>(reader);
            if (jObject == null)
                return null;

            var discriminatorValue = jObject.GetValue(_discriminatorName);
            var discriminator = discriminatorValue != null ? Newtonsoft.Json.Linq.Extensions.Value<string>(discriminatorValue) : null;
            var subtype = GetObjectSubtype(objectType, discriminator);

            var objectContract = serializer.ContractResolver.ResolveContract(subtype) as Newtonsoft.Json.Serialization.JsonObjectContract;
            if (objectContract == null || System.Linq.Enumerable.All(objectContract.Properties, p => p.PropertyName != _discriminatorName))
            {
                jObject.Remove(_discriminatorName);
            }

            try
            {
                _isReading = true;
                return serializer.Deserialize(jObject.CreateReader(), subtype);
            }
            finally
            {
                _isReading = false;
            }
        }

        private System.Type GetObjectSubtype(System.Type objectType, string discriminator)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Key == discriminator)
                    return attribute.Type;
            }

            return objectType;
        }

        private string GetSubtypeDiscriminator(System.Type objectType)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Type == objectType)
                    return attribute.Key;
            }

            return objectType.Name;
        }
    }
}
